# Generated by Django 3.0.5 on 2020-04-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='door_count',
            new_name='speed',
        ),
        migrations.AddField(
            model_name='listing',
            name='color',
            field=models.CharField(default=200, max_length=200),
            preserve_default=False,
        ),
    ]
