car_choices = {
    "NS": 'Nissan',
    "AU": 'Audi',
    "TO": 'Toyota',
    "SU": 'Subaru',
    "HO": 'Honda',
    "MI": 'Mitsubishi',
    "MB": 'Mercedes Benz',
    "MA": 'Mazda',
    "VW": 'Volkswagen',
    "BMW":  'BMW',
    "LR": 'Land Rover',
    "IS": 'Isuzu',
    "FO": 'Ford',
    "SUZ":  'Suzuki',
    "LX": 'Lexus',
    "JA": 'Jaguar',
    "JE": 'Jeep',
    "CH": 'Chevrolet',
    "CA": 'Cadillac',
    "MA": 'Maserati',
    "PE": 'Peugeot',
    "PO": 'Porsche',
    "TE": 'Tesla',
    "DE": 'Deutz',
}

price_choices = {
    '10000': '$10,000',
    '20000': '$20,000',
    '30000': '$30,000',
    '40000': '$40,000',
    '50000': '$50,000',
    '60000': '$60,000',
    '70000': '$70,000',
    '80000': '$80,000',
    '90000': '$90,000',
    '100000': '$100,000',
    '200000': '$200,000',
}

state_choices = {
    'AK': 'Alaska',
    'AL': 'Alabama',
    'AR': 'Arkansas',
    'AS': 'American Samoa',
    'AZ': 'Arizona',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DC': 'District of Columbia',
    'DE': 'Delaware',
    'FL': 'Florida',
    'GA': 'Georgia',
    'GU': 'Guam',
    'HI': 'Hawaii',
    'IA': 'Iowa',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'MA': 'Massachusetts',
    'MD': 'Maryland',
    'ME': 'Maine',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MO': 'Missouri',
    'MP': 'Northern Mariana Islands',
    'MS': 'Mississippi',
    'MT': 'Montana',
    'NA': 'National',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'NE': 'Nebraska',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'NM': 'New Mexico',
    'NV': 'Nevada',
    'NY': 'New York',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PA': 'Pennsylvania',
    'PR': 'Puerto Rico',
    'RI': 'Rhode Island',
    'SC': 'South Carolina',
    'SD': 'South Dakota',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'UT': 'Utah',
    'VA': 'Virginia',
    'VI': 'Virgin Islands',
    'VT': 'Vermont',
    'WA': 'Washington',
    'WI': 'Wisconsin',
    'WV': 'West Virginia',
    'WY': 'Wyoming'
}
